baseURL = 'https://nicode.solutions/'
languageCode = 'en-us'
title = 'nicode.solutions'
theme = 'cactus'

[params]
  colortheme = "classic" # dark, light, white, or classic
  description = "Welcome to nicode.solutions! ğŸ‰ Discover tutorials, project updates, and insights from an Italian software engineer and part-time indie hacker. Get inspired and start building! ğŸ› ï¸ğŸ’¡"
  mainSection = "posts"
  mainSectionTitle = "Blog"
  gravatar = "sillymysteriously30e72ce1aa"

[[params.social]]
  name = "twitter"
  link = "https://x.com/nicode_it"

[[params.social]]
  name = "github"
  link = "https://github.com/nicolagheza"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

